[2025-03-17T20:20:15.382+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T20:20:15.853+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_tables.events_project_a_db scheduled__2025-03-17T20:10:00+00:00 [queued]>
[2025-03-17T20:20:16.012+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_tables.events_project_a_db scheduled__2025-03-17T20:10:00+00:00 [queued]>
[2025-03-17T20:20:16.022+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-17T20:20:16.380+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): load_tables.events_project_a_db> on 2025-03-17 20:10:00+00:00
[2025-03-17T20:20:16.541+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3540) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T20:20:16.581+0000] {standard_task_runner.py:72} INFO - Started process 3565 to run task
[2025-03-17T20:20:16.631+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load_tables.events_project_a_db', 'scheduled__2025-03-17T20:10:00+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpmblpkvm1']
[2025-03-17T20:20:16.689+0000] {standard_task_runner.py:105} INFO - Job 255: Subtask load_tables.events_project_a_db
[2025-03-17T20:20:19.091+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.load_tables.events_project_a_db scheduled__2025-03-17T20:10:00+00:00 [running]> on host c032966e105e
[2025-03-17T20:20:22.671+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_tables.events_project_a_db' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T20:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-17T20:10:00+00:00'
[2025-03-17T20:20:22.781+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-17T20:20:23.421+0000] {sql.py:278} INFO - Executing: select load_tables('events_project_a_db', 'events');
[2025-03-17T20:20:23.681+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:20:24.250+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:20:24.460+0000] {sql.py:553} INFO - Running statement: select load_tables('events_project_a_db', 'events');, parameters: None
[2025-03-17T20:20:24.700+0000] {sql.py:562} INFO - Rows affected: 1
[2025-03-17T20:20:25.570+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-17T20:20:25.590+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=load_tables.events_project_a_db, run_id=scheduled__2025-03-17T20:10:00+00:00, execution_date=20250317T201000, start_date=20250317T202015, end_date=20250317T202025
[2025-03-17T20:20:26.371+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T20:20:26.500+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
