[2025-03-17T19:48:10.599+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T19:48:10.750+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_tables.pages_project_c_db scheduled__2025-03-17T19:30:00+00:00 [queued]>
[2025-03-17T19:48:10.849+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_tables.pages_project_c_db scheduled__2025-03-17T19:30:00+00:00 [queued]>
[2025-03-17T19:48:10.858+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-17T19:48:11.029+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): load_tables.pages_project_c_db> on 2025-03-17 19:30:00+00:00
[2025-03-17T19:48:11.089+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3076) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T19:48:11.118+0000] {standard_task_runner.py:72} INFO - Started process 3088 to run task
[2025-03-17T19:48:11.149+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load_tables.pages_project_c_db', 'scheduled__2025-03-17T19:30:00+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp9nnxu3vc']
[2025-03-17T19:48:11.180+0000] {standard_task_runner.py:105} INFO - Job 209: Subtask load_tables.pages_project_c_db
[2025-03-17T19:48:12.580+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.load_tables.pages_project_c_db scheduled__2025-03-17T19:30:00+00:00 [running]> on host c032966e105e
[2025-03-17T19:48:14.489+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_tables.pages_project_c_db' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T19:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-17T19:30:00+00:00'
[2025-03-17T19:48:14.500+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-17T19:48:14.799+0000] {sql.py:278} INFO - Executing: select load_tables('pages_project_c_db', 'pages');
[2025-03-17T19:48:14.880+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T19:48:14.950+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T19:48:14.999+0000] {sql.py:553} INFO - Running statement: select load_tables('pages_project_c_db', 'pages');, parameters: None
[2025-03-17T19:48:15.109+0000] {sql.py:562} INFO - Rows affected: 1
[2025-03-17T19:48:15.330+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-17T19:48:15.340+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=load_tables.pages_project_c_db, run_id=scheduled__2025-03-17T19:30:00+00:00, execution_date=20250317T193000, start_date=20250317T194810, end_date=20250317T194815
[2025-03-17T19:48:15.958+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T19:48:16.299+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-17T19:48:16.440+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-17T19:48:16.488+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
